### ISSUE TITLE
width attribute doesn't function

### ISSUE THREAD

**Issue by louayshaat** [martignoni/hugo-video#20] opened 2021-02-13 16:58 UTC
Awesome work, video width attribute doesn't take effect. I tried percentage and px

**Comment by martignoni** [comment] 2021-02-13 17:10
Cannot reproduce. Please post your source code or show your repo.

**Comment by martignoni** [comment] 2021-02-26 15:11
No feedback, can't reproduce. Closing.

**Closed as completed by martignoni** 2021-02-26 15:11 UTC
Labels: invalid
